export const UPDATE_USER = "UPDATE_USER";
export const CLEAR_USER = "CLEAR_USER";

export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";
export const SET_ACTIVE_ACTIVITY = "SET_ACTIVE_ACTIVITY";

export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const SET_ACTIVE_TASK = "SET_ACTIVE_TASK";

export const SWITCH_COLORMODE = "SWITCH_COLORMODE";
